title: Brewer's page
author: Michael Brewer
email: brewermichael208@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  my gitHub page development
# social links
twitter_username: #your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Brew906 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
---
theme: minima
---
